### ISSUE TITLE
Support for osx

### ISSUE THREAD

**Issue by grinay** [sdcb/PaddleSharp#28]
Hi, I spent few days trying to make it work on mac m1. 
The problematic part is to build paddle inference c, as I face into the issue with gflags duplicates. So I change some cmake files to make it work. 
However I see there are warning outputs: 
Warn: OSPlatform is not windows or linux, platform might not supported.
Would you like to elaborate to release osx runtime package? And remove that warning from output?:)
Made a simple package: [Sdcb.PaddleInference.runtime.osx_m1](https://www.nuget.org/packages/Sdcb.PaddleInference.runtime.osx_m1/)

**Comment by sdcb** [comment]
this is caused by following line:
https://github.com/sdcb/PaddleSharp/blob/e457c9f104d7f878c87145c42ed6faadce66dbda/src/Sdcb.PaddleInference/PaddleConfig.cs#L137

I never tested in mac, so you might have to make a code change to the line above and create a PR, I'm happy to make a nuget release of that

**Comment by sdcb** [comment]
After dig-in deeper, I think the problem might not related to this, because it is just a console output. paddle inference library is not just a single so/dll, you might have to add LD_LIBRARY_PATH or PATH before process running to support all so/dlls loaded. I tested in Linux, the SearchPathLoad is not working, in Linux environment LD_LIBRARY_PATH or PATH must been specific BEFORE process start, can't specify at runtime(but not sure mac).

I think in theory it can work, the point is what is the console output, what is the real problem.

**Comment by sdcb** [comment]
Can you confirm is it working? if you confirmed it is working then I can remove the console output.

**Comment by grinay** [comment]
Not sure how to confirm it, but we build the complex system based on paddle inference c library. 
And it's already working in our production server on linux. My goal was to make it work on my mac , because I don't like to work on windows laptop;)
Here are the OCR result output.
<img width="1368" alt="image" src="https://user-images.githubusercontent.com/13212299/208599762-201b2940-ce30-418d-94e5-48879b53a55b.png">
But as well for mac you have to install opencv by calling
brew install opencv@4 or brew install --build-from-source opencv@4
it will install some dependencies such as gflags which is required for paddle. 
The other thing is it could require the opencvsharp extern library, which I also packed here https://www.nuget.org/packages/OpenCvSharp4.runtime.osx_m1/

**Comment by sdcb** [comment]
so yo already make it running & work in mac m1 right?

**Comment by grinay** [comment]
Yes. Cpu only of course. 


Sent from Mail.ru app for iOS


Thursday, 22 December 2022 09.09 +0800 from ***@***.***  ***@***.***>:

**Comment by sdcb** [comment]
there is another question? how can you make it up and running with opencvsharp4 depedency, it seems it does not provide mac m1 in his github package lists: https://github.com/shimat/opencvsharp#native-bindings

**Comment by grinay** [comment]
I had to build it. Read message above, I provided package link. As well beed to install opencv with brew , brew install ***@***.***


Sent from Mail.ru app for iOS


Tuesday, 27 December 2022 11.25 +0800 from ***@***.***  ***@***.***>:

**Comment by sdcb** [comment]
Hi @grinay 
can you try not prefix the package name with `Sdcb`? Because I wants to use this one as a personal prefix, let's try maybe `Grinay.PaddleInference.runtime.osx_m1`?
